# Generated by Django 2.2 on 2020-05-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('description', models.TextField()),
                ('user_create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
